                <div class="panel-body">
                  <?php echo (isset($this->alert)? $this->alert: '');?>
                    <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal" method ="post">
                      <div class="form-group">
                        <label for="name" class="col-sm-3 control-label">Nome: </label>
                        <div class="col-sm-8">
                          <input type="text" name = "name" class="form-control" id="name" placeholder="Nome Completo">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">E-mail: </label>
                        <div class="col-sm-8">
                          <input required type="text" name = "email" class="form-control" id="email" placeholder="exemplo@seuemail.com.br">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">Data de Nascimento: </label>
                        <div class="col-sm-8">
                          <input required type="date" name = "data_nascimento" class="form-control" id="data_nascimento" placeholder="dd/mm/aaaa">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="username"  class="col-sm-3 control-label">Username: </label>
                        <div class="col-sm-8">
                          <input required type="text" name = "username"class="form-control" id="username" placeholder="username">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">Senha: </label>
                        <div class="col-sm-8">
                          <input required type="password" name = "password" class="form-control" id="password" placeholder="senha">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                          <button type="submit" class="btn btn-success">Cadastrar</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>