-- MySQL Script generated by MySQL Workbench
-- 01/18/17 16:16:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tourismbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tourismbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tourismbd` DEFAULT CHARACTER SET utf8 ;
USE `tourismbd` ;

-- -----------------------------------------------------
-- Table `tourismbd`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourismbd`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourismbd`.`nationalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourismbd`.`nationalities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourismbd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourismbd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 1,
  `data_nascimento` DATETIME NOT NULL,
  `role_id` INT(1) NOT NULL,
  `nationality_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_role_id_idx` (`role_id` ASC),
  INDEX `users_nacionalidade_id_idx` (`nationality_id` ASC),
  CONSTRAINT `users_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `tourismbd`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_nationality_id`
    FOREIGN KEY (`nationality_id`)
    REFERENCES `tourismbd`.`nationalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourismbd`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourismbd`.`login_attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `login_attempt_user_id_idx` (`user_id` ASC),
  CONSTRAINT `login_attempt_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tourismbd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourismbd`.`recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourismbd`.`recoveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `passwords_user_id_idx` (`user_id` ASC),
  CONSTRAINT `passwords_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tourismbd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tourismbd`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourismbd`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city_shortbreaks` FLOAT NULL DEFAULT 0,
  `gastronomia` FLOAT NULL DEFAULT 0,
  `saude_bemestar` FLOAT NULL DEFAULT 0,
  `cultural_paisagistico` FLOAT NULL DEFAULT 0,
  `natureza` FLOAT NULL DEFAULT 0,
  `negocios` FLOAT NULL DEFAULT 0,
  `religioso` FLOAT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `perfil_user_id_idx` (`user_id` ASC),
  CONSTRAINT `profile_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tourismbd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
