<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title><?php echo $view_title; ?></title>
    <!-- BOOTSTRAP CORE CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FONT-AWESOME STYLE SHEET FOR BEAUTIFUL ICONS -->
    <link href="assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM CSS -->
    <link href="assets/css/style.css" rel="stylesheet" />
     <!-- GOOGLE FONT FOR BETTER FONT STYLE -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css' />
     <!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

    <div class="scroll-me" >   <!-- just pass scroll-me class and start scrolling -->
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?php echo BASE;?>home/">
                  <img class="img-responsive" src="<?php echo IMG;?>logo.png"/>
                </a>
            </div>
        </div>
    	<section id="features-sec">
		    <div class="row">
		            <div class="panel panel-custom">
		                <div class="panel-heading">
		          		<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
						<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
						<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
						<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
						<?php 
							echo $add_css;
							echo $add_js;
						?>
						<div class="row">
						<?php echo isset($this->menu) ? $this->menu->getMenu() : ''?>
		            <!--<div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 ">-->
    					
